# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d567363a664a27d3a372342bca9028a32b38fceb86994b8024ae2e209beda826620f53e082df0ff85ad866e77136a5d0c09eb97bd7a5392dc892069ca046f45

test:
  secret_key_base: e389ace3b1b284eeaa4d7ea0ee512a2ef2dd7f1ae39c7cf9abf051d02698ff2fa1a6d0b12fcae48ea577bd8cfba34eda33a41fdcc64bf69c000e2dc47f822b3d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
